---
dependencies:
  - role: Mayeu.RabbitMQ
    rabbitmq_ssl: false
    rabbitmq_plugins:
      - rabbitmq_management
      - rabbitmq_management_agent
      - rabbitmq_shovel
      - rabbitmq_federation
      - rabbitmq_shovel_management
    rabbitmq_vhost_definitions:
      - name: /faxanadu
        tracing: yes
    rabbitmq_users_definitions:
      - vhost:    /faxanadu
        user:     user1
        password: password
        configure_priv: "^$"
        read_priv: "^$" # Disallow reading.
        write_priv: ".*" # allow writing.
      - vhost:    "{{ main_vhost }}"
        user:     admin
        password: password
        force:    no
        tags:
        - administrator
